spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://otimasqlserver.database.windows.net:1433;databaseName=OtimaSqlDB
    username: otimausr
    password: Otima@user22

  jpa:
    #hibernate:
     # ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true  
  
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1 
      
      
server :
  port : 8092
  max-http-header-size: 200000