spring:
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
  
  sleuth:   
    sampler:      probability: 1.0 
          
server :
  port : 8093
  max-http-header-size: 200000
  
request:      
      exchange:      
        producerEx : ex.producer.exchange
      routingKey:
        producerReq : rq.producer.request
        producerRes : rq.producer.response
      deadLetter:
       producerReq : dl.producer.request
